/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Inhr1.c
**     Project   : Project
**     Processor : MC9S12C32MFA25
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.15, CPU db: 2.87.402
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 18.06.2015, 19:31
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is not set in the "Safe mode". See help.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       1             |  PT0_PWM0_IOC0
**             ----------------------------------------------------
**
**         Port name                   : T
**
**         Bit number (in port)        : 0
**         Bit mask of the port        : $0001
**
**         Initial direction           : Input (direction can be changed)
**         Safe mode                   : no
**         Initial output value        : 1
**         Initial pull option         : up
**
**         Port data register          : PTT       [$0240]
**         Port control register       : DDRT      [$0242]
**
**         Optimization for            : speed
**     Contents  :
**         SetDir - void Inhr1_SetDir(bool Dir);
**         GetVal - bool Inhr1_GetVal(void);
**         PutVal - void Inhr1_PutVal(bool Val);
**         ClrVal - void Inhr1_ClrVal(void);
**         SetVal - void Inhr1_SetVal(void);
**         NegVal - void Inhr1_NegVal(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Inhr1. */

#include "Inhr1.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG Inhr1_DATA            /* Select data segment "Inhr1_DATA" */
#pragma CODE_SEG Inhr1_CODE
#pragma CONST_SEG Inhr1_CONST          /* Constant section for this module */
/*
** ===================================================================
**     Method      :  Inhr1_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool Inhr1_GetVal(void)

**  This method is implemented as a macro. See Inhr1.h file.  **
*/

/*
** ===================================================================
**     Method      :  Inhr1_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**         Note: If direction is set to input the method code may not
**               work properly.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void Inhr1_PutVal(bool Val)
{
  if (Val) {
    setReg8Bits(PTT, 0x01U);           /* PTT0=0x01U */
  } else { /* !Val */
    clrReg8Bits(PTT, 0x01U);           /* PTT0=0x00U */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  Inhr1_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**         Note: If direction is set to input the method code may not
**               work properly.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Inhr1_ClrVal(void)

**  This method is implemented as a macro. See Inhr1.h file.  **
*/

/*
** ===================================================================
**     Method      :  Inhr1_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**         Note: If direction is set to input the method code may not
**               work properly.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Inhr1_SetVal(void)

**  This method is implemented as a macro. See Inhr1.h file.  **
*/

/*
** ===================================================================
**     Method      :  Inhr1_NegVal (component BitIO)
**
**     Description :
**         This method negates (inverts) the output value.
**         Note: If direction is set to input the method code may not
**               work properly.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Inhr1_NegVal(void)

**  This method is implemented as a macro. See Inhr1.h file.  **
*/

/*
** ===================================================================
**     Method      :  Inhr1_SetDir (component BitIO)
**
**     Description :
**         This method sets direction of the component.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void Inhr1_SetDir(bool Dir)
{
  if (Dir) {
    setReg8Bits(DDRT, 0x01U);          /* DDRT0=0x01U */
  } else { /* !Dir */
    clrReg8Bits(DDRT, 0x01U);          /* DDRT0=0x00U */
  } /* !Dir */
}


/* END Inhr1. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
